// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7l_pCKBxXPzfEkXBE2HasGQKsDUiLuTw',
    appId: '1:91959307539:web:a5b9de9e4ce98258d1fee6',
    messagingSenderId: '91959307539',
    projectId: 'kyc-flow-f595f',
    authDomain: 'kyc-flow-f595f.firebaseapp.com',
    storageBucket: 'kyc-flow-f595f.firebasestorage.app',
    measurementId: 'G-BVX9CN618Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4wnz9jyHbL2OkdKHumDbOFKwJs5lGGHY',
    appId: '1:91959307539:android:9ef1ed4f7f6cbe26d1fee6',
    messagingSenderId: '91959307539',
    projectId: 'kyc-flow-f595f',
    storageBucket: 'kyc-flow-f595f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl5Yz_SVYavz9m2Ie79ipfwpFat2OwCms',
    appId: '1:91959307539:ios:cacf8ff066a031ddd1fee6',
    messagingSenderId: '91959307539',
    projectId: 'kyc-flow-f595f',
    storageBucket: 'kyc-flow-f595f.firebasestorage.app',
    iosBundleId: 'com.example.kyc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl5Yz_SVYavz9m2Ie79ipfwpFat2OwCms',
    appId: '1:91959307539:ios:cacf8ff066a031ddd1fee6',
    messagingSenderId: '91959307539',
    projectId: 'kyc-flow-f595f',
    storageBucket: 'kyc-flow-f595f.firebasestorage.app',
    iosBundleId: 'com.example.kyc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7l_pCKBxXPzfEkXBE2HasGQKsDUiLuTw',
    appId: '1:91959307539:web:70da1c981f44978ed1fee6',
    messagingSenderId: '91959307539',
    projectId: 'kyc-flow-f595f',
    authDomain: 'kyc-flow-f595f.firebaseapp.com',
    storageBucket: 'kyc-flow-f595f.firebasestorage.app',
    measurementId: 'G-XQZVGZLQCH',
  );
}
